Cases about negative captcha on the feedback page
IgorSasovets/wdio-project pull request #3
Opened 2020-03-20 09:15 UTC by TetianaGagan

2020-03-20 12:43 UTC, TetianaGagan commented
@IgorSasovets please check my PR

2020-03-22 09:45 UTC, IgorSasovets requested changes
@TetianaGagan , not bad. Please take a look at my comments. Please draw your attention to naming, typos and fix them.

2020-03-22 09:45 UTC, IgorSasovets commented on pages/JuiceShop/feedbackPage.js
> +    get commentField() {return browser.$('#comment');}
Small typos, `{return browser.$('#comment');}` ==> `{ return browser.$('#comment'); }`

2020-03-22 09:45 UTC, IgorSasovets commented on pages/JuiceShop/feedbackPage.js
> +        return this.waitForElement(this.commentField);
What is the purpose of this wait???

2020-03-22 09:45 UTC, IgorSasovets commented on pages/JuiceShop/feedbackPage.js
> +    get errorCaptchaMessage() {return browser.$('.ng-tns-c123-9>.mat-error');}
It would be better to rename it to `captchaErrorMessage`

2020-03-22 09:45 UTC, IgorSasovets commented on pages/JuiceShop/feedbackPage.js
> +    get dismissButton() {return browser.$('.mat-focus-indicator.close-dialog');}
I guess, it should be changed to `dismissModalButton`

2020-03-22 09:45 UTC, IgorSasovets commented on pages/JuiceShop/feedbackPage.js
> +    async typeCaptchaResultfield(captcha) {
Please rename to `fillCaptcha` or `resolveCaptcha`

2020-03-22 09:45 UTC, IgorSasovets commented on tests/juice_shope_negative_leave_feedback.spec.js
> +        const errorMessage = FeedbackPage.errorCaptchaMessage;
You should use `await` here because `FeedbackPage.errorCaptchaMessage` returns promise that should be resolved

2021-07-23 14:49 UTC, closed without merging