Added tests show and hide items for score board page
IgorSasovets/wdio-project pull request #5
Opened 2020-03-26 13:26 UTC by InnaO

2020-03-26 13:51 UTC, InnaO commented
@IgorSasovets Please, look at my PR?

2020-03-26 14:20 UTC, IgorSasovets requested changes
@InnaO , good job. Please add minor fixes and it will be resolved as done

2020-03-26 14:20 UTC, IgorSasovets commented on pages/basePage.js
> +    async waitForElement(element, { timeout = 5000, retries = 10 } = {}) {
Please remove unnecessary white spaces

2020-03-26 14:20 UTC, IgorSasovets commented on tests/score-board.spec.js
> +    before(async () => {
Please remove white space after `async`, the same is actual for the `it` blocks descriptions

2020-03-26 14:45 UTC, InnaO reviewed
@IgorSasovets I have added fixes to my PR. Please, review

2020-03-26 15:42 UTC, IgorSasovets requested changes
@InnaO , please see my comments

2020-03-26 15:42 UTC, IgorSasovets commented on pages/basePage.js
> -
Why did you remove this line?

2020-03-26 15:42 UTC, IgorSasovets commented on pages/basePage.js
> -
Also, change
```
async waitForElement(element, { timeout = 5000, retries = 10 } = {})
```
to
```
async waitForElement(element, {timeout = 5000, retries = 10} = {})
```

2020-03-26 15:42 UTC, IgorSasovets commented on tests/score-board.spec.js
> -    it('Should change challenge items visibility to hide all ', async () => {
```
it('Should change challenge items visibility to hide all ', async() => {
```
to
```
it('Should change challenge items visibility to hide all', async() => {
```

2020-03-27 08:01 UTC, InnaO reviewed
@IgorSasovets sorry, it was my mistake
Please, check again

2020-03-27 08:05 UTC, IgorSasovets approved these changes

2020-03-27 08:06 UTC, merged